### ISSUE TITLE
milestone not rendered at the right place on the timeline

### ISSUE THREAD

**Issue by reidlw** [pln-planning-tools/MapLight#39] opened 2022-10-24 20:34 UTC
when I navigate here: https://maplight.vercel.app/roadmap/github.com/ipfs/roadmap/issues/95

you'll see that the "libipfs" issue is not rendered where expected on the timeline

**Comment by AlexxNica** [comment] 2022-10-25 19:39
Duplicate of https://github.com/pln-planning-tools/MapLight/issues/38

**Closed by AlexxNica** 2022-10-25 19:39 UTC
